// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQfDQ-spVMq2UdQxiet68LQGYs6cOK_E',
    appId: '1:346269912426:web:212bf530da66bf7af36913',
    messagingSenderId: '346269912426',
    projectId: 'geoattendanceapp-8b039',
    authDomain: 'geoattendanceapp-8b039.firebaseapp.com',
    storageBucket: 'geoattendanceapp-8b039.firebasestorage.app',
    measurementId: 'G-G20EM80RHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMa0emO6BITu4HqOsvxUpK1GYk0wKp6E',
    appId: '1:346269912426:android:79d527f7f2d7e6f0f36913',
    messagingSenderId: '346269912426',
    projectId: 'geoattendanceapp-8b039',
    storageBucket: 'geoattendanceapp-8b039.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCss8zCo8VgoINGlGr1w88oAEcG1pzvYsY',
    appId: '1:346269912426:ios:5bd7b77594885d94f36913',
    messagingSenderId: '346269912426',
    projectId: 'geoattendanceapp-8b039',
    storageBucket: 'geoattendanceapp-8b039.firebasestorage.app',
    iosBundleId: 'com.example.bioauthAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCss8zCo8VgoINGlGr1w88oAEcG1pzvYsY',
    appId: '1:346269912426:ios:5bd7b77594885d94f36913',
    messagingSenderId: '346269912426',
    projectId: 'geoattendanceapp-8b039',
    storageBucket: 'geoattendanceapp-8b039.firebasestorage.app',
    iosBundleId: 'com.example.bioauthAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQfDQ-spVMq2UdQxiet68LQGYs6cOK_E',
    appId: '1:346269912426:web:2347c7ed1d69543df36913',
    messagingSenderId: '346269912426',
    projectId: 'geoattendanceapp-8b039',
    authDomain: 'geoattendanceapp-8b039.firebaseapp.com',
    storageBucket: 'geoattendanceapp-8b039.firebasestorage.app',
    measurementId: 'G-RD0HVKQRTC',
  );
}
